CREATE TABLE IF NOT EXISTS master_style_types (
    id SERIAL PRIMARY KEY,
    master_id INT NOT NULL,
    style_type_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);